# .travis.yml
language: ruby
rvm:
  - 2.3.1
env:
  - DB=postgresql
cache: bundler
addons:
  postgresql: "9.4"
services:
  - postgresql
script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=development bundle exec rake db:create db:migrate db:seed
