
development:
  adapter: postgresql
  encoding: unicode
  database: credit_control_development
  host: localhost
  pool: 5
  username: postgres
  password: 


test:
  adapter: postgresql
  encoding: unicode
  database: credit_control_test
  host: localhost
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: credit_control_production
  host: localhost
  pool: 5
  username: postgres
  password: 
